// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9owI-mH9y847W6d_aGyeUGRl7QVYPF6I',
    appId: '1:677012134579:web:384ef8fe7a540510f6aec6',
    messagingSenderId: '677012134579',
    projectId: 'jobwaroeng-a78c9',
    authDomain: 'jobwaroeng-a78c9.firebaseapp.com',
    storageBucket: 'jobwaroeng-a78c9.firebasestorage.app',
    measurementId: 'G-NNN4X8EJ6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtllhy5KGm4h4ye0uxDWMNkuM12xWSwf4',
    appId: '1:677012134579:android:aabf58e3e3189e90f6aec6',
    messagingSenderId: '677012134579',
    projectId: 'jobwaroeng-a78c9',
    storageBucket: 'jobwaroeng-a78c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcuVDKoRsQWAjfR12jLvNXxMjlR90O4CY',
    appId: '1:677012134579:ios:bcee3ada2b1e3fd0f6aec6',
    messagingSenderId: '677012134579',
    projectId: 'jobwaroeng-a78c9',
    storageBucket: 'jobwaroeng-a78c9.firebasestorage.app',
    androidClientId: '677012134579-ie0v06qpo9uk8uqkcdieed79548m7768.apps.googleusercontent.com',
    iosClientId: '677012134579-jpm9mpvl51f0u9ko0n5i8os7elqe1he5.apps.googleusercontent.com',
    iosBundleId: 'com.example.noPoverty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcuVDKoRsQWAjfR12jLvNXxMjlR90O4CY',
    appId: '1:677012134579:ios:bcee3ada2b1e3fd0f6aec6',
    messagingSenderId: '677012134579',
    projectId: 'jobwaroeng-a78c9',
    storageBucket: 'jobwaroeng-a78c9.firebasestorage.app',
    androidClientId: '677012134579-ie0v06qpo9uk8uqkcdieed79548m7768.apps.googleusercontent.com',
    iosClientId: '677012134579-jpm9mpvl51f0u9ko0n5i8os7elqe1he5.apps.googleusercontent.com',
    iosBundleId: 'com.example.noPoverty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9owI-mH9y847W6d_aGyeUGRl7QVYPF6I',
    appId: '1:677012134579:web:f349f4fece8dfefbf6aec6',
    messagingSenderId: '677012134579',
    projectId: 'jobwaroeng-a78c9',
    authDomain: 'jobwaroeng-a78c9.firebaseapp.com',
    storageBucket: 'jobwaroeng-a78c9.firebasestorage.app',
    measurementId: 'G-23179S3Y4E',
  );
}
