// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmKlsurIGZQlSO0XgOkM7jaVtYe6yB0j8',
    appId: '1:626050383133:web:7c954f7652203407b735f4',
    messagingSenderId: '626050383133',
    projectId: 'jobwaroeng',
    authDomain: 'jobwaroeng.firebaseapp.com',
    storageBucket: 'jobwaroeng.firebasestorage.app',
    measurementId: 'G-7BW0WPN8GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKq5fXIMg1TxLAcuRsxP9RlF37x6vdFko',
    appId: '1:626050383133:android:0fcadad3e000c9b5b735f4',
    messagingSenderId: '626050383133',
    projectId: 'jobwaroeng',
    storageBucket: 'jobwaroeng.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO9s953L0mZ6SEOkKdciK4JjNnUzAmY6g',
    appId: '1:626050383133:ios:5b3e3768e3616dd0b735f4',
    messagingSenderId: '626050383133',
    projectId: 'jobwaroeng',
    storageBucket: 'jobwaroeng.firebasestorage.app',
    iosBundleId: 'com.example.noPoverty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO9s953L0mZ6SEOkKdciK4JjNnUzAmY6g',
    appId: '1:626050383133:ios:5b3e3768e3616dd0b735f4',
    messagingSenderId: '626050383133',
    projectId: 'jobwaroeng',
    storageBucket: 'jobwaroeng.firebasestorage.app',
    iosBundleId: 'com.example.noPoverty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmKlsurIGZQlSO0XgOkM7jaVtYe6yB0j8',
    appId: '1:626050383133:web:8431dfa4e536d852b735f4',
    messagingSenderId: '626050383133',
    projectId: 'jobwaroeng',
    authDomain: 'jobwaroeng.firebaseapp.com',
    storageBucket: 'jobwaroeng.firebasestorage.app',
    measurementId: 'G-94YD64C3Z2',
  );
}
